MODEL:
  TYPE: nuclei
  NAME: nuclei_test
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 18
    EMBED_DIM_Y : 512
    DEPTHS: [ 2, 2, 2, 2, 2, 6 ]
    DEPTHS_Y: [ 0, 0, 0, 0, 0, 0 ]
    MIX_DEPTH: [0, 0, 0, 0, 0, 0 ]
    NUM_HEADS: [ 3, 6, 12, 12, 12, 24 ]
    MIX_HEADS: [ 0, 0, 0, 16, 32, 64 ]
    WINDOW_SIZE: 7